[[redirects]]
from = "/proxyNaver/*"
to = "https://api.finance.naver.com/siseJson.naver/:splat"  
status = 200
force = true


[[redirects]]
from = "/proxyDart/*"
to = "https://opendart.fss.or.kr/api/:splat"  
status = 200
force = true